# Generated by Django 2.1.4 on 2019-02-27 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduGalaxyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=50)),
                ('user_pwd', models.CharField(max_length=15)),
                ('user_nickname', models.CharField(max_length=15)),
                ('user_age', models.IntegerField()),
                ('user_job', models.CharField(max_length=30)),
                ('user_sex', models.BooleanField()),
                ('user_address1', models.CharField(max_length=100)),
                ('user_address2', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_receive_email', models.BooleanField()),
                ('user_confirm', models.BooleanField()),
                ('user_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_signup_ip', models.CharField(max_length=100)),
            ],
        ),
    ]
