# Generated by Django 2.1.4 on 2019-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduGalaxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edugalaxyuser',
            name='user_email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='이메일'),
        ),
    ]
