# Generated by Django 2.1.4 on 2019-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduGalaxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edugalaxyuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='관리자'),
        ),
    ]
