# Generated by Django 2.1.4 on 2019-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduGalaxy', '0002_auto_20190305_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edugalaxyuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='활성화 여부'),
        ),
    ]
