# Generated by Django 2.1.4 on 2019-07-30 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=100, verbose_name='학교로고 파일명')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성날짜')),
                ('created_ip', models.CharField(max_length=20, verbose_name='게시판 생성 ip')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='수정날짜')),
                ('modified_ip', models.CharField(max_length=20, verbose_name='게시판 수정 ip')),
                ('edu_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성날짜')),
                ('created_ip', models.CharField(max_length=20, verbose_name='게시판 생성 ip')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='수정날짜')),
                ('modified_ip', models.CharField(max_length=20, verbose_name='게시판 수정 ip')),
                ('adminPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.AdminPost')),
                ('edu_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
