# Generated by Django 2.1.4 on 2019-07-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admin/schoolCSV', verbose_name='파일명')),
                ('title', models.TextField(default='', verbose_name='파일 용도')),
            ],
        ),
    ]
