# Generated by Django 2.1.4 on 2019-07-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name': '학교', 'verbose_name_plural': '학교 리스트'},
        ),
    ]
