# Generated by Django 2.1.4 on 2019-08-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_adminpost_userpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='school_info',
            new_name='admin_post',
        ),
    ]
