# Generated by Django 2.1.4 on 2019-08-02 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190802_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
