# Generated by Django 2.1.4 on 2019-08-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20190802_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='logo',
            field=models.CharField(max_length=100, null=True, verbose_name='학교로고 파일명'),
        ),
    ]
