# Generated by Django 2.1.4 on 2019-08-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190802_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='admin_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.AdminPost'),
        ),
    ]
