# Generated by Django 2.1.4 on 2019-03-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edugalaxyuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='활성화 여부'),
        ),
    ]
