# Generated by Django 2.1.4 on 2019-03-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190318_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edugalaxyuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
    ]
