# Generated by Django 2.1.4 on 2019-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190322_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edugalaxyuser',
            name='user_sex',
            field=models.CharField(default='U', max_length=2, verbose_name='성별'),
        ),
    ]
