# Generated by Django 2.1.4 on 2019-04-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190403_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edugalaxyuser',
            old_name='user_sex',
            new_name='user_gender',
        ),
    ]
