# Generated by Django 2.1.4 on 2019-04-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190410_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edugalaxyuser',
            name='user_nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='닉네임'),
        ),
    ]
