# Generated by Django 2.1.4 on 2019-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='생성날짜'),
        ),
    ]
